services:

  frontend:
    build:
      context: .
      dockerfile: Streamlit_Frontend/pages/Dockerfile
    image: frontend:latest
    ports:
      - "8502:8501"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: FastAPI_Backend/Dockerfile
    image: backend:latest
    ports:
      - "8000:8080"

networks:
  default:
    name: diet_project_network